In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data = pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
# Preprocess the data
data = data.drop(["RowNumber", "CustomerId", "Surname"], axis=1)

In [4]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data["Gender"] = label_encoder_gender.fit_transform(data["Gender"])

In [5]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [6]:
# One-hot encode 'Geography'
onehot_encoder_geo = OneHotEncoder(handle_unknown="ignore")
geo_encoded = onehot_encoder_geo.fit_transform(data[["Geography"]]).toarray()
geo_encoded_df = pd.DataFrame(
    geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(["Geography"])
)
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [7]:
# Combine one-hot encoded columns with original data
data = pd.concat([data.drop("Geography", axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [8]:
# Split the data into features and target
X = data.drop("EstimatedSalary", axis=1)
y = data["EstimatedSalary"]

In [9]:
## Split the data in training and tetsing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [10]:
## Scale these features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
# Save the encoders and scaler for later use
with open("label_encoder_gender.pkl", "wb") as file:
    pickle.dump(label_encoder_gender, file)

with open("onehot_encoder_geo.pkl", "wb") as file:
    pickle.dump(onehot_encoder_geo, file)

with open("scaler.pkl", "wb") as file:
    pickle.dump(scaler, file)

#### ANN Regression Problem statement

In [12]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
# Build the model
model = Sequential(
    [
        Dense(64, activation="relu", input_shape=(X_train.shape[1],)),
        Dense(32, activation="relu"),
        Dense(1),  # Output layer for regression
    ]
)

## compile the model
model.compile(optimizer="adam", loss="mean_absolute_error", metrics=["mae"])

model.summary()

c:\Users\ribhav.jain\AppData\Local\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [15]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(
    monitor="val_loss", patience=10, restore_best_weights=True
)

In [16]:
# Train the model
history = model.fit(
    X_train,
    y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback],
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 100082.5703 - mae: 100082.5703 - val_loss: 98505.3047 - val_mae: 98505.3047
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 99620.0312 - mae: 99620.0312 - val_loss: 96804.3281 - val_mae: 96804.3281
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 96173.6016 - mae: 96173.6016 - val_loss: 92447.0234 - val_mae: 92447.0234
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 93301.2812 - mae: 93301.2812 - val_loss: 85334.7500 - val_mae: 85334.7500
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 84963.2969 - mae: 84963.2969 - val_loss: 76349.3047 - val_mae: 76349.3047
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 75980.0859 - mae: 75980.0859 - val_loss: 67362.6484 - val_mae: 67362.6484
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 66066.0234 - mae: 66066.0234 - val_loss: 59846.8281 - val_mae: 59846.8281
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 58380.5312 - mae: 58380.5312 - val_loss: 54754.0156 - val_mae: 54754.0156
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 54469.9609 - mae: 54469.9609 - val_loss: 52240.7422 - val_mae: 52240.7422
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 51748.0312 - mae: 51748.0312 - val_loss: 51281.5273 - val_mae: 51281.5273
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 51444.7422 - mae: 51444.7422 - val_loss: 50924.0430 - val_mae: 50924.0430
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50216.8555 - mae: 50216.8555 - val_loss: 50794.3242 - val_mae: 50794.3242
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50731.1641 - mae: 50731.1641 - val_loss: 50719.6836 - val_mae: 50719.6836
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50201.6367 - mae: 50201.6367 - val_loss: 50655.2969 - val_mae: 50655.2969
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50768.9531 - mae: 50768.9531 - val_loss: 50606.8086 - val_mae: 50606.8086
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50068.2812 - mae: 50068.2812 - val_loss: 50560.5898 - val_mae: 50560.5898
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50199.6016 - mae: 50199.6016 - val_loss: 50521.3438 - val_mae: 50521.3438
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49466.7930 - mae: 49466.7930 - val_loss: 50480.1953 - val_mae: 50480.1953
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49574.5820 - mae: 49574.5820 - val_loss: 50448.1914 - val_mae: 50448.1914
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50268.0742 - mae: 50268.0742 - val_loss: 50422.9609 - val_mae: 50422.9609
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49723.1172 - mae: 49723.1172 - val_loss: 50391.6055 - val_mae: 50391.6055
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49541.0078 - mae: 49541.0078 - val_loss: 50366.7266 - val_mae: 50366.7266
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49497.7695 - mae: 49497.7695 - val_loss: 50344.8242 - val_mae: 50344.8242
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49867.6172 - mae: 49867.6172 - val_loss: 50325.4414 - val_mae: 50325.4414
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49461.1250 - mae: 49461.1250 - val_loss: 50308.8281 - val_mae: 50308.8281
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49640.1641 - mae: 49640.1641 - val_loss: 50298.0391 - val_mae: 50298.0391
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49274.4219 - mae: 49274.4219 - val_loss: 50281.4414 - val_mae: 50281.4414
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49522.1016 - mae: 49522.1016 - val_loss: 50281.0352 - val_mae: 50281.0352
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49464.9766 - mae: 49464.9766 - val_loss: 50267.7852 - val_mae: 50267.7852
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49723.3047 - mae: 49723.3047 - val_loss: 50266.3828 - val_mae: 50266.3828
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49522.8242 - mae: 49522.8242 - val_loss: 50262.8945 - val_mae: 50262.8945
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49722.5312 - mae: 49722.5312 - val_loss: 50255.7109 - val_mae: 50255.7109
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49920.1797 - mae: 49920.1797 - val_loss: 50255.0039 - val_mae: 50255.0039
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49898.8242 - mae: 49898.8242 - val_loss: 50258.2266 - val_mae: 50258.2266
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49843.9961 - mae: 49843.9961 - val_loss: 50253.6680 - val_mae: 50253.6680
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49546.7344 - mae: 49546.7344 - val_loss: 50243.5977 - val_mae: 50243.5977
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49240.1250 - mae: 49240.1250 - val_loss: 50248.0352 - val_mae: 50248.0352
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49721.0156 - mae: 49721.0156 - val_loss: 50246.3047 - val_mae: 50246.3047
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49326.8203 - mae: 49326.8203 - val_loss: 50233.7070 - val_mae: 50233.7070
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49549.6055 - mae: 49549.6055 - val_loss: 50241.8320 - val_mae: 50241.8320
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49789.3320 - mae: 49789.3320 - val_loss: 50233.5586 - val_mae: 50233.5586
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49613.2305 - mae: 49613.2305 - val_loss: 50233.8164 - val_mae: 50233.8164
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49394.5273 - mae: 49394.5273 - val_loss: 50232.2617 - val_mae: 50232.2617
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49345.4219 - mae: 49345.4219 - val_loss: 50232.5703 - val_mae: 50232.5703
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49594.6055 - mae: 49594.6055 - val_loss: 50224.8086 - val_mae: 50224.8086
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49832.5039 - mae: 49832.5039 - val_loss: 50227.3945 - val_mae: 50227.3945
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 48898.1562 - mae: 48898.1562 - val_loss: 50228.5703 - val_mae: 50228.5703
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49747.9375 - mae: 49747.9375 - val_loss: 50230.3906 - val_mae: 50230.3906
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50012.4102 - mae: 50012.4102 - val_loss: 50224.6406 - val_mae: 50224.6406
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49519.0508 - mae: 49519.0508 - val_loss: 50219.1562 - val_mae: 50219.1562
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49131.9805 - mae: 49131.9805 - val_loss: 50227.9844 - val_mae: 50227.9844
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49822.0859 - mae: 49822.0859 - val_loss: 50230.4766 - val_mae: 50230.4766
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49870.5508 - mae: 49870.5508 - val_loss: 50225.8164 - val_mae: 50225.8164
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49207.9336 - mae: 49207.9336 - val_loss: 50232.3555 - val_mae: 50232.3555
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 48993.5469 - mae: 48993.5469 - val_loss: 50226.3047 - val_mae: 50226.3047
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 48987.7617 - mae: 48987.7617 - val_loss: 50240.7617 - val_mae: 50240.7617
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49380.4336 - mae: 49380.4336 - val_loss: 50239.9492 - val_mae: 50239.9492
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49626.1289 - mae: 49626.1289 - val_loss: 50240.3359 - val_mae: 50240.3359
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49146.3906 - mae: 49146.3906 - val_loss: 50233.5352 - val_mae: 50233.5352
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49606.4766 - mae: 49606.4766 - val_loss: 50235.5352 - val_mae: 50235.5352

In [17]:
%load_ext tensorboard

In [18]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 21024), started 0:03:50 ago. (Use '!kill 21024' to kill it.)

In [19]:
## Evaluate model on the test data
test_loss, test_mae = model.evaluate(X_test, y_test)
print(f"Test MAE : {test_mae}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 806us/step - loss: 51105.4102 - mae: 51105.4102
Test MAE : 50219.15625

In [20]:
model.save("regression_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.